name: Generate contribution snake

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: Platane/snk@d8f6715049803e982ee5ff501b6b9b7d5deeb09b # v3.5.0
        id: snake
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            output/github-contribution-grid-snake-dark.svg?palette=github-dark
            output/github-contribution-grid-snake.svg

      - name: Push snake output
        uses: peaceiris/actions-gh-pages@373f7f263a76c20808c831209c920827a82a2847 # v3.9.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: output
          publish_dir: ./output
          commit_message: "chore: update contribution snake"
